// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI agent that generates a compelling salon description.
 *
 * - generateSalonDescription - A function that handles the salon description generation.
 * - GenerateSalonDescriptionInput - The input type for the generateSalonDescription function.
 * - GenerateSalonDescriptionOutput - The return type for the generateSalonDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSalonDescriptionInputSchema = z.object({
  salonName: z.string().describe('The name of the salon.'),
  serviceDescription: z.string().describe('Detailed description of the salon services.'),
  atmosphereDescription: z.string().describe('Description of the salon atmosphere.'),
  targetCustomerDescription: z.string().describe('Description of the target customer.'),
  uniqueSellingPoints: z.string().describe('Unique selling points of the salon.'),
});
export type GenerateSalonDescriptionInput = z.infer<typeof GenerateSalonDescriptionInputSchema>;

const GenerateSalonDescriptionOutputSchema = z.object({
  salonDescription: z.string().describe('A compelling description of the salon.'),
});
export type GenerateSalonDescriptionOutput = z.infer<typeof GenerateSalonDescriptionOutputSchema>;

export async function generateSalonDescription(
  input: GenerateSalonDescriptionInput
): Promise<GenerateSalonDescriptionOutput> {
  return generateSalonDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSalonDescriptionPrompt',
  input: {schema: GenerateSalonDescriptionInputSchema},
  output: {schema: GenerateSalonDescriptionOutputSchema},
  prompt: `You are an expert marketing copywriter for beauty salons. Your task is to create a compelling and attractive description for a salon based on the information provided.

Salon Name: {{salonName}}
Services: {{serviceDescription}}
Atmosphere: {{atmosphereDescription}}
Target Customer: {{targetCustomerDescription}}
Unique Selling Points: {{uniqueSellingPoints}}

Write a salon description that will attract customers and highlight the unique qualities of the salon. The description should be concise, engaging, and no more than 150 words.
`,
});

const generateSalonDescriptionFlow = ai.defineFlow(
  {
    name: 'generateSalonDescriptionFlow',
    inputSchema: GenerateSalonDescriptionInputSchema,
    outputSchema: GenerateSalonDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
